const ACTION_EVENTS_FETCH = 'EVENTS_FETCH';
const ACTION_EVENTS_FETCH_SUCCESS = 'EVENTS_FETCH_SUCCESS';
const ACTION_EVENTS_FETCH_ERROR = 'EVENTS_FETCH_ERROR';
const ACTION_EVENTS_FILTER = 'ACTION_EVENTS_FILTER';
const ACTION_EVENTS_MY_EVENTS = 'ACTION_EVENTS_MY_EVENTS'
export {
    ACTION_EVENTS_FETCH,
    ACTION_EVENTS_FETCH_SUCCESS,
    ACTION_EVENTS_FETCH_ERROR,
    ACTION_EVENTS_FILTER,
    ACTION_EVENTS_MY_EVENTS
}